### ISSUE TITLE
Please provide a LICENSE file

### ISSUE THREAD

**Issue by mnhauke** [t-brown/mcds#10]
I've been trying to work out what license mcds is under.
Most files contain a header that states that it licensed under "GPLv3 or any later version".

But I can't see a LICENSE file in the repository.

I suspect that mcds is completely licensed under the "GPL-3.0-or-later" license, but I think this needs to be made completely clear.

Thanks.

**Comment by t-brown** [comment]
I've added a top-level LICENSE file (GPLv3) in PR #11
