### ISSUE TITLE
Google CardDAV URL Showing 404

### ISSUE THREAD

**Issue by Ge0rg3** [t-brown/mcds#15]
Hi,

Thanks for this project.

When trying to access Google's CardDAV URL with any gmail address, a 404 is just returned to me:
https://www.googleapis.com/carddav/v1/principals/username@example.com/lists/default

I have a feeling that this has been deprecated by Google, but I can't find any notice by them that this is the case.

Thanks

**Comment by t-brown** [comment]
Thanks for open an issue.
Interestingly the URL still works for a Google business account.
There seems to be conflicting information on their site.

- https://developers.google.com/contacts/carddav/ 
- https://developers.google.com/calendar/caldav/v2/guide

The first one says to do a `PROPFIND` on the `.well-known/carddav`, when I do that I still get the URL you mention.

```
statler ~$ curl --user 'tbrown@somecompany.com:token' -i -X PROPFIND https://www.googleapis.com/.well-known/carddav
HTTP/2 301 
content-type: text/plain; charset=UTF-8
x-content-type-options: nosniff
pragma: no-cache
x-xss-protection: 1; mode=block
expires: Mon, 01 Jan 1990 00:00:00 GMT
cache-control: no-cache, no-store, max-age=0, must-revalidate
location: /carddav/v1/principals/tbrown@somecompany.com/lists/default/
x-frame-options: SAMEORIGIN
vary: Origin
vary: X-Origin
vary: Referer
date: Sat, 16 Jan 2021 18:06:29 GMT
server: ESF
content-length: 0
alt-svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"

```

Are you able to run that `curl` command and provide the location? In the meantime, I'll start changing `mcds` to use the `PROPFIND`.

**Comment by Ge0rg3** [comment]
Oh, didn't know about PROPFIND 👍 
For me, the PROPFIND request works, but then sending a GET to the url in the location header still returns a 404. I'll agree that the Chrome documentation on CardDAV is really lacking and no longer up to date :(

**Comment by t-brown** [comment]
Everything I'm reading seems to indicate it should still work. Are you able to run `mcds` in verbose mode and provide any de-identified information?

**Comment by Ge0rg3** [comment]
Nvm turns out its because I was testing things with GET, and google expected a POST 😄 not sure why they chose 404 instead of 405.
Thanks for the help!
