### ISSUE TITLE
rc.c: ‘strncpy’ output truncated before terminating nul copying as many bytes from a string as its length

### ISSUE THREAD

**Issue by andy-bower** [t-brown/mcds#23]
With hardening options, gcc-11.4 to gcc-13.3, at least, report:

```
gcc -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H   -I/usr/include/x86_64-linux-gnu  -I/usr/include/libxml2   -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -ffile-prefix-map=/home/andy/git/mcds=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wall -pedantic -Werror -Wno-error=date-time -c -o mcds-rc.o `test -f 'rc.c' || echo './'`rc.c
In file included from /usr/include/string.h:535,
                 from rc.c:34:
In function ‘strncpy’,
    inlined from ‘read_rc’ at rc.c:127:6:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:10: error: ‘strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |                                   __glibc_objsize (__dest));
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
rc.c: In function ‘read_rc’:
rc.c:122:39: note: length computed here
  122 |                                 len = strlen(tmp);
      |                                       ^~~~~~~~~~~
cc1: all warnings being treated as errors
```
Issue replaces PR #18.

**Comment by andy-bower** [comment]
https://github.com/t-brown/mcds/blob/3fec633d83fd84337c023c99f2faff8818fdc9a9/src/rc.c#L120-L134

I believe the compiler is correct within the scope of that function: yes, strsep() replaces the delimiter with nul but the issue is that `strncpy()` is copying `strlen(tmp)` bytes which does not include the delimiter. Adding one to the length supplied to `strncpy()` as I proposed, does fix this.

However, knowing the `xmalloc()` zeroes the destination, we can be sure this is not a problem in practice. So patching this is only an exercising in appeasing the compiler, which is probably worth doing.

Related issue in line 125 not an issue in practice due to the `xmalloc()`.

**However, I wonder if we can simplify all this by including `\n` as one of the delimiters?** Then we wouldn't need the conditional at all.

[edit: deleted erroneous concern about too-long config lines - although they might be nice to produce an error for rather than just truncating]

**Comment by t-brown** [comment]
Appeasing compilers is always a good thing. Also adding `\n` is a great idea. I never thought of that for some reason. Thanks!
