### ISSUE TITLE
Confusing Documentation Regarding netrc

### ISSUE THREAD

**Issue by levlaz** [t-brown/mcds#3]
The manpage states that `netrc` is enabled by default. However, when I tried to connect to a nextcloud server with a working netrc file, I see the following in the debug output. 

```
levlaz@Levs-MacBook-Pro ~ % mcds -v -u https://cloud.levops.io/remote.php/carddav/addressbooks/levlaz/contacts Test
mcds options are:
  URL        : https://cloud.levops.io/remote.php/carddav/addressbooks/levlaz/contacts
  SSL Verify : 0
  Use .netrc : 0
  Username   : (null)
  Password   : (null)
  Query term : Test
  Query      : FN
  Search     : EMAIL
  Sending    :
<?xml version='1.0' encoding='utf-8' ?>
```

Which indicates that netrc is not enabled. 

Once I add `netrc=yes` to a .mcdsrc file, things work as expected. 

This is happening on version `mcds (GNU mcds) 1.2` - it appears that either the docs or wrong or this default setting is not working.

**Comment by t-brown** [comment]
Thanks for the bug report!
PR #4 addresses this and has been merged to master.
