### ISSUE TITLE
No configure

### ISSUE THREAD

**Issue by Xylon2** [t-brown/mcds#7]
When pulling the code using the following command:
`git clone https://github.com/t-brown/mcds.git`

There is no configure script, only a configure.ac

And thanks for this cool project.

**Comment by t-brown** [comment]
Yes, since this is source code only, I do not commit a `configure` script. To create one from the repo you'll need to run `autoreconf` from the GNU Autotools.

**Comment by t-brown** [comment]
If you do want a version that has `configure` in it, please use a release, for example the latest is [mcds-1.4.tar.gz](https://github.com/t-brown/mcds/releases/download/v1.4/mcds-1.4.tar.gz).

**Comment by Xylon2** [comment]
Oh OK silly me.
